variable "resource_group" {}
variable "location" {}
variable "web_subnet_id" {}
variable "app_subnet_id" {}
variable "db_subnet_id" {}
variable "mgmt_subnet_id" {}
variable "webcount" {}
variable "appcount" {}
variable "dbcount" {}
variable "username" {}
variable "password" {}
